# Generated by Django 5.1.15 on 2026-06-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ENROLLMENT', 'New Enrollment'), ('NEW_LESSON', 'New Lesson'), ('QA_ANSWER', 'Q&A Answer'), ('REFUND', 'Refund'), ('ANNOUNCEMENT', 'Announcement'), ('COURSE_APPROVED', 'Course Approved'), ('MENTOR_APPROVED', 'Mentor Approved'), ('REVIEW', 'New Review')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, default='', help_text='Frontend route to navigate to', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
